-- 코드를 작성해주세요
# SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR,
# (
#     SELECT MAX(SIZE_OF_COLONY)
#     FROM ECOLI_DATA AS B
#     WHERE YEAR(B.DIFFERENTIATION_DATE) = YEAR(A.DIFFERENTIATION_DATE)
# ) - A.SIZE_OF_COLONY AS YEAR_DEV,
#     A.ID
# FROM ECOLI_DATA AS A
# ORDER BY YEAR, YEAR_DEV

WITH YearlyMax AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
           MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT 
    YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
    (ym.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM 
    ECOLI_DATA e
JOIN 
    YearlyMax ym ON YEAR(e.DIFFERENTIATION_DATE) = ym.YEAR
ORDER BY 
    YEAR ASC, 
    YEAR_DEV ASC;